### ISSUE TITLE
Refactor assertEquals to asserThat

### ISSUE THREAD

**Issue by Tonypsilon** [Tonypsilon/bmm.backend#1]
Replace all usages of assertEquals (from JUnit) with assertThat (from AssertJ) to have the tests written more uniformly

**Comment by ujwalkumar1995** [comment]
Hey @Tonypsilon 
I would like to work on this issue.
Could you please assign it to me?

**Comment by Tonypsilon** [comment]
PR is merged, thanks for the contribution!
