### ISSUE TITLE
Enhance Venue controller for venue maintenance

### ISSUE THREAD

**Issue by Tonypsilon** [Tonypsilon/bmm.backend#15]
As a club admin, I want to update all my playing venues at once so that the usage of the API becomes more user friendly and efficient and less error prone.

- [x] The VenueController offers a PUT endpoint that accepts a List of VenueData.
- [x] The venues may either exist, or not yet.
- [x] When the creation or update of any venue fails, no venue is updated at all and a BmmException with a suitable error message is returned.
- [x] A controller test is created to verify the functionality.

**Comment by ishridharhegde** [comment]
Hi, I'd like to work on this issue.

**Comment by Tonypsilon** [comment]
Hi, sry I already started working on it as it is quite urgent.
