### ISSUE TITLE
Remove default values from annotations

### ISSUE THREAD

**Issue by Tonypsilon** [Tonypsilon/bmm.backend#7]
At some places in the code, redundant default parameters are used for annotations.
Example: `@Column(unique = false, nullable = false)` where unique = false can be deleted.

- [ ] Delete all redundant default parameters of annotations

**Comment by vishalsingh2972** [comment]
@Tonypsilon can you assign this to me if it's open?

**Comment by Tonypsilon** [comment]
@vishalsingh2972 have fun :-)

**Comment by vishalsingh2972** [comment]
@Tonypsilon any specific packages/subpackages ?

**Comment by vishalsingh2972** [comment]
Done @Tonypsilon could you please check and merge the PR https://github.com/Tonypsilon/bmm.backend/pull/11

**Comment by vishalsingh2972** [comment]
> At some places in the code, redundant default parameters are used for annotations. Example: `@Column(unique = false, nullable = false)` where unique = false can be deleted.
> 
> * [ X]  Delete all redundant default parameters of annotations

**Comment by vishalsingh2972** [comment]
> At some places in the code, redundant default parameters are used for annotations. Example: `@Column(unique = false, nullable = false)` where unique = false can be deleted.
> 
> * [x]  Delete all redundant default parameters of annotations

Done @Tonypsilon could you please check and merge the PR https://github.com/Tonypsilon/bmm.backend/pull/11

**Comment by vishalsingh2972** [comment]
> At some places in the code, redundant default parameters are used for annotations. Example: `@Column(unique = false, nullable = false)` where unique = false can be deleted.
> 
> * [x]  Delete all redundant default parameters of annotations

Done @Tonypsilon could you please check and merge the PR https://github.com/Tonypsilon/bmm.backend/pull/11

**Comment by Tonypsilon** [comment]
Hi @vishalsingh2972, `unique=false` is an example, there is more like `nullable = true` (found this for example in Match.java). Your IDE should give you a hint regarding "redundant default parameter", in IntelliJ for example the value is shown in grey font to indicate this.

**Comment by vishalsingh2972** [comment]
> Hi @vishalsingh2972, `unique=false` is an example, there is more like `nullable = true` (found this for example in Match.java). Your IDE should give you a hint regarding "redundant default parameter", in IntelliJ for example the value is shown in grey font to indicate this.

I actually checked all ,but couldn't find anything else apart from unique=false that was redundant 👍

**Comment by vishalsingh2972** [comment]
Thanks for the info @Tonypsilon , have checked thoroughly and made the changes that you requested can you please check the PR #11

**Comment by vishalsingh2972** [comment]
> Hi @vishalsingh2972, `unique=false` is an example, there is more like `nullable = true` (found this for example in Match.java). Your IDE should give you a hint regarding "redundant default parameter", in IntelliJ for example the value is shown in grey font to indicate this.

Thanks for the info @Tonypsilon , have checked thoroughly and made the changes that you requested can you please check the PR https://github.com/Tonypsilon/bmm.backend/pull/11

**Comment by vishalsingh2972** [comment]
> Hi @vishalsingh2972, `unique=false` is an example, there is more like `nullable = true` (found this for example in Match.java). Your IDE should give you a hint regarding "redundant default parameter", in IntelliJ for example the value is shown in grey font to indicate this.

Thanks for the info @Tonypsilon , have checked thoroughly and made the changes that you requested can you please check the PR https://github.com/Tonypsilon/bmm.backend/pull/11

**Comment by vishalsingh2972** [comment]
> Hi @vishalsingh2972, `unique=false` is an example, there is more like `nullable = true` (found this for example in Match.java). Your IDE should give you a hint regarding "redundant default parameter", in IntelliJ for example the value is shown in grey font to indicate this.

Thanks for the info @Tonypsilon , have checked thoroughly and made the changes that you requested can you please check the PR https://github.com/Tonypsilon/bmm.backend/pull/11

**Comment by vishalsingh2972** [comment]
done the changes that you requested @Tonypsilon can you check PR #11
